upload:
    path: /upload
    controller: App\Controller\UploadController::upload
ping:
    path: /ping
    controller: App\Controller\PingController::ping
status:
    path: /status
    controller: App\Controller\StatusController::status